language: node_js
node_js:
  - "0.12"
before_install :
 - "npm install -g mocha"
 - "npm install codecov"
 - "npm install chai"
install :
 - "npm install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
