language: node_js
node_js:
  - "0.12"
env:
 - NODE_ENV=test
before_install:
 - "npm install mocha"
 - "npm install chai"
 - "npm install codecov"
install:
 - "npm install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
